name: aSense
options:
  bundleIdPrefix: com.momstudios
  deploymentTarget:
    iOS: "17.0"
targets:
  aSense:
    type: application
    platform: iOS
    sources:
      - path: aSense
        excludes:
          - Info.plist
    settings:
      base:
        INFOPLIST_FILE: aSense/Info.plist
        CODE_SIGN_ENTITLEMENTS: aSense/aSense.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.momstudios.asense
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: "NO"
